name: Deploy node application

on:
    push:
        branches:
            - main
    
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{secrets.DOCKER_USERNAME}}
              password: ${{secrets.DOCKER_PASSWORD}}
          - name: Build and push
            uses: docker/build-push-action@v6
            with:
              push: true
              tags: prajwaludpdi0/dashnode:latest
              

    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Pull image from docker hub
              run: docker pull prajwaludpdi0/dashnode:latest
            - name: Run the container
              run: docker run -d -p 5001:5001 --name dashnodejs-app-container -e MONGO_URL= ${{secrets.MONGO_URL}} -e PORT= ${{secrets.PORT}}
                   prajwaludpdi0/dashnode